apiVersion: "ryax.tech/v2.0"
kind: Processor
spec:
  id: romeoaction
  human_name: romeo
  type: python3
  version: "1.4"
  description: "Offloading sur Romeo"
  categories:
  - HPC
  inputs: 
  - help: Private key file content.
    human_name: ssh_pkey
    name: ssh_pkey
    type: file
  - help: Username.
    human_name: ssh_user
    name: ssh_user
    type: string
  - help: Remote host.
    human_name: ssh_host
    name: ssh_host
    type: string
  - help: Ssh port.
    human_name: ssh_port
    name: ssh_port
    type: integer
  - help: exec
    human_name: exec name
    name: exec
    type: "string"
  outputs:
  - help: Code d'erreur
    human_name: error
    name: err
    type: "string"
   
    
        
