apiVersion: "ryax.tech/v2.0"
kind: Processor
spec:
  id: test_hpc
  human_name: Action_hpc
  type: python3
  version: "1.3"
  description: "Test_hpc"
  categories:
  - HPC 
  spec:
    addons:
        hpc: {}
        
