apiVersion: "ryax.tech/v2.0"
kind: Processor
spec:
  id: testhpc
  human_name: Action_hpc
  type: python3
  version: "1.4"
  description: "Test_hpc"
  categories:
  - HPC 
  inputs: 
  - help: sshname
    human_name: name
    name: sshname
    type: "string"
  - help: sship
    human_name: ip
    name: ip
    type: "string"
  - help: exec
    human_name: exec name
    name: exec
    type: "string"
  outputs:
  - help: execname
    human_name: exec
    name: exec
    type: "string"
   
    
        
