apiVersion: "ryax.tech/v2.0"
kind: Processor
spec:
  id: calcul
  human_name: Déploiement de calculs
  type: python3
  version: "1.0"
  description: "Déploiement de vos calculs sur une machine adéquate"
  categories:
  - HPC
  inputs: 
  - help: Clé privée ssh RSA.
    human_name: ssh_pkey
    name: ssh_pkey
    type: file
  - help: Nom d'utilisateur
    human_name: ssh_user
    name: ssh_user
    type: string
  - help: Time nécessaire maximum pour le calcul, format jj:hh:mm:ss
    human_name: Temps
    name: time
    type: "string"
    default_value: "00:10:00"
  - help: Nombre de noeuds demandés
    human_name: nodes
    name: nodes
    type: integer
    default_value: 1
  - help: Nombre de coeurs demandés 
    human_name: cores
    name: num_cores
    type: "integer"
    default_value: 1
  - help: Type de ressource demandée 
    human_name: cpu_or_gpu
    name: resource
    type: enum
    enum_values:
      - cpu
      - gpu
    default_value: cpu
  outputs:
  - help: Error(s)
    human_name: Code(s) d'erreur
    name: err
    type: "string"
  - help: Ressources
    human_name: Ressources dispo
    name: res_DEBUG
    type: "string"
   
    
        
