apiVersion: "ryax.tech/v2.0"
kind: Processor
spec:
  id: rapatdata
  human_name: Récupération de données 
  type: python3
  version: "1.4"
  description: "Récupération des données de sortie de calcul stockée dans un fichier sur la machine vers la vôtre "
  categories:
  - HPC 
  inputs: 
  - help: sshname
    human_name: name
    name: sshname
    type: "string"
  - help: sship
    human_name: ip
    name: ip
    type: "enum"
    enum_values: 
      - dgx1.univ-reims.fr
      - romeologin1.univ-reims.fr
      - romeologin2.univ-reims.fr
  - help: Path du fichier résultat sur la machine de calcul, depuis votre home
    human_name: output_name + extension
    name: remote_location
    type: "string"
  - help: Path du fichier résultat sur votre machine 
    human_name: output_name + extension
    name: home_location
    type: "string"
  outputs:
  - help: Code d'erreur
    human_name: error
    name: err
    type: "string"
  - help: Sortie
    human_name: Sortie
    name: out
    type: "string"

   
    
        
